// The optional FPT.AI central-Vietnamese files can be generated by their
// licensed creator; never enable that pack without its real MP3 assets.
export const CENTRAL_VOICE_READY = false;

// Piper VAIS1000 files are generated/verified in GitHub Actions before Vite
// compiles the site. The flag is off for local builds without those files.
export const PIPER_VOICE_READY = import.meta.env.VITE_PIPER_VOICE_READY === 'true';
